DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10

MAX_PAGE_SIZE = 100

DEFAULT_REORDER_LEVEL = 10

MAX_CATEGORY_NAME_LENGTH = 50
MAX_CATEGORY_DESCRIPTION_LENGTH = 255

MAX_SUPPLIER_NAME_LENGTH = 100
MAX_EMAIL_LENGTH = 100
MAX_PHONE_LENGTH = 15
MAX_ADDRESS_LENGTH = 255

MAX_PRODUCT_NAME_LENGTH = 100
MAX_SKU_LENGTH = 30